os: linux
dist: xenial

matrix:
  include:
    - language: php

      php:
      - 7.4

      addons:
        chrome: stable

      services: mysql

      before_install:
        - mysql -e 'CREATE DATABASE fronds_test;'

      install:
        - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
        - chmod +x php-coveralls.phar
        - cp .env.ci .env
        - travis_retry composer install --no-interaction --prefer-dist --no-suggest
        - php artisan key:generate
        - php artisan dusk:chrome-driver 81
        - php artisan migrate
        - npm install

      before_script:
        - npm run dev
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
        - php artisan serve &

      script:
#        - php artisan dusk
        - ./vendor/bin/phpunit
      after_success:
        - travis_retry php php-coveralls.phar -vvv

    - language: node_js

      node_js:
        - 10.15

      install:
        - npm install
        - travis_retry npm install --global eslint @vue/cli
        - npm run dev

      script:
        - npm run lint

